apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJR25lN0syOVhpSUl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMU1USXdNVFV5TWpoYUZ3MHpOVEExTVRBd01UVTNNamhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNvamFUNWRvTHBEOERmMDJPZlJ3bHZFTkJwWXV5THFEMmV6THdpRmNuaDVkVk1EUU1YMjlER1duVU0KSXUrYk81ZTdhZWJzTkVHMU1Ic1owRkVlT1daUDFxWnI5YTlUL2NKZkR1Q3JvQlhZVzNrUjBabWl0c0pIYjVsdQo0MFNRWU8zbTRJUzdrQVFMVUg2SUpsMm1VUm1DSHgwZDRsSWNvLytyK3VTN2lTTGo2c1RiakUyUjVzOVhzNlVnCi83UUZsWXZ5OXVGNkN4MG11NkI1Q1FtN0t4NEdsRk51bzFtcENLMGxiUHBPNFNzYTF1NldTRm9HcjNQWldoZSsKa2kzN3kzSVZUTk9UM2I4L2VHT3IyYTBRQTZwWkgyemZ5Mjlsdi8vejBBY1d0TG5vVUZLYUZNdThUc0hIelV6YwppbnNUR0x3QkwyZ2VCckpOdXVXL3hETWI1U1lGQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUaGVvNFpDbXFuMTlFQWFoa2oveHdxd2h4U2h6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQW1mVS9sODR3Mwp4Y2IrM0w0aEtoTGswNHVHb1dUR1pEbXZDMjkwcTF4Q2FiVmdlL2gxbnU5VU5xamtwM0tKR3QrNm1MVDBKMURmCkRaWmVQazNzLzRJdEUraXEyUG1LU1V3eUhvMVBkZ3ZnWkJwR2lwSldlT0NHdEhEVFBCSnlNN3BLMDhZY2t4aVgKVFFrZ0ppVExTQkM1cWNDZ1VnV2lNdnVNdVgyUWJ0V2VWUEk0c3ZUdVo3RjA1MEhCWG5xMHNPQ2taSCtvMmZwbwpsOHJLU2trWHNLaWwrbGdXMmhQaHljZHgrcXpPTmhscG51bDEwSmloV0JCaTN5WklRRjE1eTNRc1NWY28ySWNiClJRMUx4aHhiTm9IN0lROGpuNkxuUXZ2SExkSGtDWHJMN2RHMGdYaGF1dU8vOVVUdUJ6aUxtMThocU9URklra1EKZVc0K3FVTWxsYTFOCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://886D27DEE886F2AFD63E5E66E49A2C50.gr7.ap-southeast-1.eks.amazonaws.com
  name: youtube-cluster.ap-southeast-1.eksctl.io
contexts:
- context:
    cluster: youtube-cluster.ap-southeast-1.eksctl.io
    user: KyawZin@youtube-cluster.ap-southeast-1.eksctl.io
  name: KyawZin@youtube-cluster.ap-southeast-1.eksctl.io
current-context: KyawZin@youtube-cluster.ap-southeast-1.eksctl.io
kind: Config
preferences: {}
users:
- name: KyawZin@youtube-cluster.ap-southeast-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - youtube-cluster
      - --region
      - ap-southeast-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      interactiveMode: IfAvailable
      provideClusterInfo: false
